# Establece la imagen base para Java
FROM openjdk:11-jdk-slim

# Configura el directorio de trabajo
WORKDIR /Preguntados

# Copia el archivo JAR de tu aplicación a la imagen
COPY target/Preguntados-0.0.1-SNAPSHOT.jar Preguntados-0.0.1-SNAPSHOT.jar

# Copia el archivo de configuración de la base de datos (si es necesario)
COPY src/main/resources/application.properties application.properties

# Expone el puerto en el que tu aplicación escucha (ajústalo según tus necesidades)
EXPOSE 8080

# Comando para ejecutar tu aplicación Java
CMD ["java", "-jar", "Preguntados-0.0.1-SNAPSHOT.jar"]
